### ISSUE TITLE
Неправильно считается НДС

### ISSUE THREAD

**Issue by Zherlick** [anthonyaxenov/atol-online#1]
Добрый день.

Неправильно считается НДС20, да и с остальными проблема по идее.
Класс Vat:
```php
switch ($type) {
            case VatTypes::NONE:
            case VatTypes::VAT0:
                return 0;
            case VatTypes::VAT10:
                //return $kopeks * 10 / 100;
            case VatTypes::VAT110:
                return $kopeks * 10 / 110;
            case VatTypes::VAT18:
                //return $kopeks * 18 / 100;
            case VatTypes::VAT118:
                return $kopeks * 18 / 118;
            case VatTypes::VAT20:
---->>>     //return $kopeks * 20 / 100;
            case VatTypes::VAT120:
                return $kopeks * 20 / 120;
        }
        return 0;
```

Себе поправил, но после этого заметил - неправильно происходит округление налога при подсчете:
Вывод `$doc->jsonSerialize();` перед отправкой.

```
    array(8) {
      ["name"]=>
      string(52) "Тест"
      ["price"]=>
      float(252.43)
      ["quantity"]=>
      float(1)
      ["sum"]=>
      float(252.43)
      ["measurement_unit"]=>
      string(4) "шт"
      ["payment_method"]=>
      string(12) "full_payment"
      ["payment_object"]=>
      string(7) "service"
      ["vat"]=>
      array(2) {
        ["type"]=>
        string(5) "vat20"
        ["sum"]=>
        float(50.48)
      }
    }
```
Хотя по правилам должно быть 252.43 * 20 / 100 = 50.486 (50.4**9**)

**Comment by anthonyaxenov** [comment]
Если обратиться, например, [сюда](https://nalog-nalog.ru/nds/nalogovaya_baza_nds/kak-schitat-nds-pravilno-vychislyaem-20-ot-summy-primer-algoritm/):
> 1) Посчитать НДС в том числе — это значит выделить налог, который заложен в итоговую сумму. Здесь для вычисления используют формулы:
> НДС = С / 120 × 20 — если нужно посчитать НДС 20% (с 01.01.2019),
> НДС = С / 118 × 18 — если нужно посчитать НДС 18% (до 01.01.2019),
> НДС = С / 110 × 10 — если ставка налога 10%,
> Где: С — сумма, включающая НДС.
> 2) Посчитать сумму с НДС можно, не вычисляя предварительно сам налог. Для этого используйте формулы:
> С = НБ × 1,20 — если считать НДС по ставке 20% (с 01.01.2019),
> С = НБ × 1,18 — если считать НДС по ставке 18% (до 01.01.2019),
> С = НБ × 1,10 — по ставке 10%,
> где НБ — налоговая база, то есть сумма без налога.

То есть `VAT10`, `VAT18` и `VAT20` возможно и должны считаться иначе, но почему я закомментировал эти строки -- не помню, ранее они работали.

Я сейчас оперативно заняться исправлением не могу, присылайте пул-реквесты со своими исправлениями и тестами.

**Comment by anthonyaxenov** [comment]
В версиях v0.* исправляться не будет. Присылайте PR.

**Comment by anthonyaxenov** [comment]
Исправлено в v1.0.0
