### ISSUE TITLE
Ошибка формирования ставки НДС для "без НДС" и "НДС - 0" в чеках коррекции

### ISSUE THREAD

**Issue by komantnick** [anthonyaxenov/atol-online#4]
В JSON операции чека коррекции прихода, в отличие от чека прихода, обязательно наличие массива vats.
https://online.atol.ru/files/API_atol_online_v4.pdf
В классе Vats, метод calculator для НДС  none и vat0 возвращается значение 0.
Для чека коррекции необходимо, чтобы возвращалась сумма платежей без НДС или с НДС 0 процентов.
НО: для чека прихода/возврата прихода необходимо, чтобы возвращалось 0, иначе выйдет ошибка "Несоответствие НДС сумме платежей"

Пример - сумма без НДС 100 рублей
В JSON чека коррекции должно быть:
```json
"vats":[
 {
 "type":"none",
 "sum":100
 },
]
```
А в чеке прихода:
```json
"vats":[
 {
 "type":"none",
 "sum":0
 },
]
```
Или как-то так. 

Чек коррекции с некорректной суммой без НДС, пробитый через реп
![Снимок экрана от 2021-05-24 18-53-21](https://user-images.githubusercontent.com/14231512/119337382-583c7800-bcc1-11eb-91a9-e03133925f6c.png)

**Comment by anthonyaxenov** [comment]
Обсуждение в #3

**Comment by anthonyaxenov** [comment]
В версиях v0.* исправляться не будет. Присылайте PR для исправления бага в этой версии.

**Comment by anthonyaxenov** [comment]
Обязательность ставок НДС для чеков коррекции реализована в v1.0.0.

Однако согласно примеру на стр 33 [документации](https://online.atol.ru/files/API_atol_online_v4.pdf), размер НДС для коррекций вычисляется также, как для приходов и пр. Иных явных требований не указывается.

> Для чека коррекции необходимо, чтобы возвращалась сумма платежей без НДС или с НДС 0 процентов.
НО: для чека прихода/возврата прихода необходимо, чтобы возвращалось 0, иначе выйдет ошибка "Несоответствие НДС сумме платежей"

Полагаю, ошибка говорит сама за себя.
